Repository python-cmd2/cmd2, pull requests merged in 2018-12, with the labels that each got.

#604 Made it so default_to_shell results in do_shell being called so that output can be captured
  cmd2/cmd2.py
  tests/conftest.py
  tests/test_cmd2.py
Labels: enhancement

#605 Moved some class specific code out of __init__
  cmd2/cmd2.py
Labels: enhancement, minor

#612 Fixed bug in cmd2.Cmd.select() when user enters 0 or negative number
  CHANGELOG.md
  cmd2/cmd2.py
  tests/test_cmd2.py
Labels: bug
