Repository python-cmd2/cmd2, pull requests merged in 2018-03, with the labels that each got.

#291 Tab completion
  cmd2.py
  examples/python_scripting.py
  examples/subcommands.py
  examples/tab_completion.py
  tests/test_completion.py
Labels: enhancement

#292 Removed abbrev attribute
  CHANGELOG.md
  README.md
  cmd2.py
  docs/freefeatures.rst
  docs/settingchanges.rst
  examples/example.py
  examples/transcripts/exampleSession.txt
  examples/transcripts/transcript_regex.txt
  setup.py
  tests/conftest.py
  tests/scripts/postcmds.txt
  tests/scripts/precmds.txt
  tests/test_cmd2.py
  tests/test_parsing.py
  tests/test_transcript.py
  tests/transcripts/regex_set.txt
Labels: enhancement

#294 Use pytest-forked module for Linux CI
  CHANGELOG.md
  CONTRIBUTING.md
  setup.py
  tests/test_cmd2.py
  tox.ini
Labels: enhancement

#295 Removed support for case-insensitive command parsing
  .pytest_cache/v/cache/lastfailed
  CHANGELOG.md
  README.md
  cmd2.py
  docs/settingchanges.rst
  examples/case_sensitive.py
  setup.py
  tests/test_cmd2.py
  tests/test_completion.py
  tests/test_parsing.py
Labels: enhancement

#301 submenu autocomplete
  cmd2.py
  tests/test_completion.py
Labels: bug

#304 Add option to cancel the current line on keyboard interrupt.
  cmd2.py
  tests/test_cmd2.py
Labels: enhancement

#305 AddSubMenu should work with default kwargs
  cmd2.py
  tests/test_submenu.py
Labels: bug

#307 Added documentation for quit_on_sigint
  docs/settingchanges.rst
Labels: documentation, enhancement

#310 Added table_display.py
  CHANGELOG.md
  cmd2.py
  docs/conf.py
  examples/table_display.py
  setup.py
  tests/test_cmd2.py
Labels: enhancement, minor

#311 remove history line in select when user insert choice
  cmd2.py
Labels: bug

#314 Alias
  .pytest_cache/v/cache/lastfailed
  CHANGELOG.md
  README.md
  cmd2.py
  docs/freefeatures.rst
  docs/settingchanges.rst
  tests/conftest.py
  tests/test_cmd2.py
  tests/test_completion.py
  tests/test_parsing.py
  tests/test_transcript.py
  tests/transcripts/from_cmdloop.txt
Labels: enhancement

#316 Sub complete tests
  docs/argument_processing.rst
  examples/subcommands.py
  tests/test_argparse.py
Labels: enhancement

#318 Default on shell unit tests
  cmd2.py
  examples/pirate.py
  tests/test_completion.py
Labels: enhancement

#319 Added ability to specify a startup_script in cmd2.Cmd.__init__()
  CHANGELOG.md
  README.md
  cmd2.py
  docs/freefeatures.rst
  docs/settingchanges.rst
  examples/.cmd2rc
  examples/alias_startup.py
Labels: enhancement

#320 Startup script: fixed small typos and changed example code class name
  docs/freefeatures.rst
Labels: documentation, enhancement

#323 Added default sigint handler
  cmd2.py
  examples/subcommands.py
  tests/test_cmd2.py
Labels: enhancement

#324 Added an extra check to ppaged() to make sure in a real terminal
  cmd2.py
  examples/paged_output.py
Labels: enhancement

#325 Added preference for gnureadline Python module when available
  cmd2.py
  docs/index.rst
  docs/install.rst
Labels: documentation, enhancement

#326 Fix unit tests on macOS when gnureadline is installed
  tests/test_argparse.py
  tests/test_completion.py
Labels: bug

#328 Allow quoted file paths when redirecting with < and >
  cmd2.py
Labels: bug

#329 New quoted completion
  CHANGELOG.md
  README.md
  cmd2.py
  docs/freefeatures.rst
  docs/requirements.txt
  examples/paged_output.py
  examples/python_scripting.py
  examples/remove_unused.py
  examples/subcommands.py
  examples/tab_completion.py
  setup.py
  tests/test_argparse.py
  tests/test_completion.py
  tox.ini
Labels: enhancement, major
