Repository python-cmd2/cmd2, pull requests merged in 2018-07, with the labels that each got.

#465 Allow onecmd to accept a raw string for backward compatibility with cmd
  CHANGELOG.md
  cmd2/cmd2.py
  tests/test_cmd2.py
Labels: bug

#466 Deleted the CmdResult helper class
  .appveyor.yml
  CHANGELOG.md
  cmd2/cmd2.py
  cmd2/utils.py
  tox.ini
Labels: enhancement, minor

#467 History clear
  CHANGELOG.md
  cmd2/cmd2.py
  cmd2/utils.py
  tests/conftest.py
  tests/test_cmd2.py
Labels: enhancement

#468 Added unit tests for persistent history file
  tests/test_cmd2.py
Labels: enhancement

#462 Add methods to register hooks, for better plugin support
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  cmd2/cmd2.py
  cmd2/constants.py
  cmd2/parsing.py
  cmd2/plugin.py
  docs/conf.py
  docs/hooks.rst
  docs/install.rst
  docs/integrating.rst
  setup.py
  tests/test_cmd2.py
  tests/test_parsing.py
  tests/test_plugin.py
Labels: enhancement, major

#480 Add missing dependency on attrs to docs/requirements.txt
  docs/requirements.txt
Labels: bug, documentation

#485 Add tests which verify documentation build
  .travis.yml
  cmd2/cmd2.py
  docs/conf.py
  docs/requirements.txt
  examples/alias_startup.py
  setup.py
  tox.ini
Labels: documentation, enhancement, major
