Repository python-cmd2/cmd2, pull requests merged in 2018-09, with the labels that each got.

#510 Unrestrict Sphinx version since they fixed their bug
  setup.py
  tox.ini
Labels: documentation

#505 Fixed bug where alias was dropping quotes
  CHANGELOG.md
  README.md
  cmd2/cmd2.py
  cmd2/parsing.py
  docs/argument_processing.rst
  tests/conftest.py
  tests/test_cmd2.py
  tests/test_parsing.py
Labels: bug

#511 Reduce redundant definition of dependencies
  setup.py
  tox.ini
Labels: enhancement, minor

#517 Fix a couple minor lint warnings
  cmd2/cmd2.py
  cmd2/transcript.py
  examples/alias_startup.py
  examples/transcripts/exampleSession.txt
  examples/transcripts/transcript_regex.txt
Labels: minor

#528 Fix attr.ib() usage so it works with older versions of attrs
  cmd2/parsing.py
  setup.py
Labels: bug

#526 Minor improvements to CONTRIBUTING.md; no substantial content changes
  CONTRIBUTING.md
  README.md
Labels: documentation, enhancement

#525 The set command now tab-completes the setting names
  CHANGELOG.md
  cmd2/cmd2.py
  cmd2/utils.py
  tests/test_cmd2.py
  tests/test_utils.py
Labels: enhancement, minor

#529 Travis CI tests now run with official Python 3.7 instead of development version
  .travis.yml
Labels: enhancement, minor

#531 Removed remaining type hints in docstrings
  cmd2/argcomplete_bridge.py
  cmd2/argparse_completer.py
  cmd2/cmd2.py
  cmd2/utils.py
  examples/python_scripting.py
  examples/table_display.py
  tests/conftest.py
Labels: documentation, enhancement

#532 Fixed case where hints with no text printed
  cmd2/argparse_completer.py
Labels: bug

#534 Fixed several hack classes built to simulate file descriptors
  cmd2/pyscript_bridge.py
  cmd2/transcript.py
  cmd2/utils.py
  tests/conftest.py
  tests/test_argparse.py
  tests/test_autocompletion.py
  tests/test_cmd2.py
  tests/test_completion.py
  tests/test_plugin.py
  tests/test_pyscript.py
  tests/test_transcript.py
  tests/test_utils.py
Labels: bug, enhancement

#536 Prevent :param and :return type lines from showing in help summaries
  cmd2/cmd2.py
  tests/test_cmd2.py
Labels: enhancement

#535 Replace static image link with link to YouTube video
  README.md
Labels: enhancement

#538 Fix pyscript related unit tests
  cmd2/cmd2.py
  tests/test_cmd2.py
  tests/test_pyscript.py
Labels: bug, enhancement

#540 Deleted the hook methods which were deprecated in the previous release
  CHANGELOG.md
  cmd2/cmd2.py
  docs/hooks.rst
  docs/integrating.rst
  tests/test_cmd2.py
  tests/test_plugin.py
Labels: enhancement

#539 Alert printer
  CHANGELOG.md
  README.md
  cmd2/cmd2.py
  cmd2/rl_utils.py
  docs/unfreefeatures.rst
  examples/async_printing.py
  tests/test_cmd2.py
Labels: enhancement

#516 Colorize
  CHANGELOG.md
  cmd2/cmd2.py
  cmd2/constants.py
  docs/settingchanges.rst
  docs/unfreefeatures.rst
  examples/colors.py
  examples/pirate.py
  examples/plumbum_colors.py
  examples/python_scripting.py
  examples/transcripts/exampleSession.txt
  examples/transcripts/transcript_regex.txt
  tests/conftest.py
  tests/scripts/postcmds.txt
  tests/scripts/precmds.txt
  tests/test_cmd2.py
  tests/transcripts/regex_set.txt
Labels: enhancement, major

#549 Convert aliases from a class attribute to an instance attribute
  cmd2/cmd2.py
Labels: bug

#550 Added macros
  .gitignore
  CHANGELOG.md
  README.md
  cmd2/argparse_completer.py
  cmd2/cmd2.py
  cmd2/parsing.py
  cmd2/pyscript_bridge.py
  cmd2/utils.py
  docs/settingchanges.rst
  examples/.cmd2rc
  examples/arg_print.py
  examples/hooks.py
  main.py
  setup.py
  tests/conftest.py
  tests/test_autocompletion.py
  tests/test_cmd2.py
  tests/test_completion.py
  tests/test_parsing.py
  tests/test_pyscript.py
  tests/transcripts/from_cmdloop.txt
Labels: enhancement
