Repository python-cmd2/cmd2, pull requests merged in 2018-08, with the labels that each got.

#494 Matches sorted
  CHANGELOG.md
  README.md
  cmd2/argparse_completer.py
  cmd2/cmd2.py
  cmd2/utils.py
  examples/tab_autocompletion.py
  tests/test_completion.py
  tests/test_utils.py
Labels: enhancement

#491 Removed non-working Module Index link from the main Sphinx docs page
  docs/Makefile
  docs/index.rst
  tasks.py
Labels: bug, documentation

#496 Fix #495 by allowing embedded newlines in unclosed quote marks when entering multiline commands
  cmd2/cmd2.py
  cmd2/parsing.py
  tests/test_cmd2.py
  tests/test_parsing.py
Labels: bug

#503 Deleted a line which was added to support the SubMenu feature
  cmd2/cmd2.py
Labels: enhancement, minor

#508 ACHelpFormatter now inherits from argparse.RawTextHelpFormatter
  CHANGELOG.md
  cmd2/argparse_completer.py
  cmd2/cmd2.py
  examples/tab_autocompletion.py
  tests/conftest.py
  tests/test_autocompletion.py
  tests/test_cmd2.py
Labels: enhancement
