Repository python-cmd2/cmd2, pull requests merged in 2018-05, with the labels that each got.

#379 Pyscript Revamp
  CHANGELOG.md
  cmd2/__init__.py
  cmd2/argcomplete_bridge.py
  cmd2/argparse_completer.py
  cmd2/cmd2.py
  cmd2/pyscript_bridge.py
  cmd2/utils.py
  docs/freefeatures.rst
  docs/settingchanges.rst
  examples/alias_startup.py
  examples/arg_print.py
  examples/argparse_example.py
  examples/environment.py
  examples/event_loops.py
  examples/example.py
  examples/help_categories.py
  examples/paged_output.py
  examples/persistent_history.py
  examples/pirate.py
  examples/python_scripting.py
  examples/remove_unused.py
  examples/subcommands.py
  examples/submenus.py
  examples/tab_autocompletion.py
  examples/tab_completion.py
  examples/table_display.py
  tests/conftest.py
  tests/pyscript/bar1.py
  tests/pyscript/foo1.py
  tests/pyscript/foo2.py
  tests/pyscript/foo3.py
  tests/pyscript/foo4.py
  tests/pyscript/help.py
  tests/pyscript/help_media.py
  tests/pyscript/media_movies_add1.py
  tests/pyscript/media_movies_add2.py
  tests/pyscript/media_movies_list1.py
  tests/pyscript/media_movies_list2.py
  tests/pyscript/media_movies_list3.py
  tests/pyscript/media_movies_list4.py
  tests/pyscript/media_movies_list5.py
  tests/pyscript/media_movies_list6.py
  tests/pyscript/media_movies_list7.py
  tests/scripts/recursive.py
  tests/test_argparse.py
  tests/test_cmd2.py
  tests/test_completion.py
  tests/test_parsing.py
  tests/test_pyscript.py
  tests/test_submenu.py
  tests/test_transcript.py
  tests/transcripts/regex_set.txt
Labels: enhancement

#370 Switch parsing logic from pyparsing to shlex
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  cmd2/cmd2.py
  cmd2/constants.py
  cmd2/parsing.py
  cmd2/utils.py
  docs/freefeatures.rst
  docs/requirements.txt
  docs/settingchanges.rst
  docs/unfreefeatures.rst
  examples/arg_print.py
  examples/argparse_example.py
  examples/example.py
  examples/pirate.py
  setup.py
  tests/redirect.txt
  tests/test_argparse.py
  tests/test_cmd2.py
  tests/test_completion.py
  tests/test_parsing.py
  tests/test_transcript.py
  tox.ini
Labels: bug, enhancement, major

#389 Rename some test functions to fix #388
  tests/test_completion.py
Labels: bug

#403 Added check to support a continuous run of a terminator to end a line
  cmd2/parsing.py
  tests/test_parsing.py
Labels: bug, enhancement

#405 Pyscript updates
  cmd2/cmd2.py
  cmd2/pyscript_bridge.py
  tests/pyscript/bar1.py
  tests/pyscript/custom_echo.py
  tests/pyscript/foo1.py
  tests/pyscript/foo2.py
  tests/pyscript/foo3.py
  tests/pyscript/foo4.py
  tests/pyscript/help.py
  tests/pyscript/help_media.py
  tests/pyscript/media_movies_add1.py
  tests/pyscript/media_movies_add2.py
  tests/pyscript/media_movies_list1.py
  tests/pyscript/media_movies_list2.py
  tests/pyscript/media_movies_list3.py
  tests/pyscript/media_movies_list4.py
  tests/pyscript/media_movies_list5.py
  tests/pyscript/media_movies_list6.py
  tests/pyscript/media_movies_list7.py
  tests/pyscript/pyscript_dir1.py
  tests/pyscript/pyscript_dir2.py
  tests/scripts/recursive.py
  tests/test_pyscript.py
Labels: enhancement

#420 Fixed bug where preparse() wasn't called before parsing
  CHANGELOG.md
  cmd2/cmd2.py
  docs/hooks.rst
Labels: bug, minor
