Repository python-cmd2/cmd2, pull requests merged in 2018-04, with the labels that each got.

#347 Add wcwidth for setuptools>=18 and build universal wheels
  setup.cfg
  setup.py
Labels: bug, enhancement

#348 Help categories
  cmd2.py
  docs/argument_processing.rst
  examples/help_categories.py
  tests/conftest.py
  tests/test_cmd2.py
Labels: enhancement

#351 Pass the return value back through for wrapped functions.
  cmd2.py
Labels: bug

#352 User expansion
  cmd2.py
  tests/test_completion.py
Labels: enhancement, minor

#353 Unhackify
  .gitignore
  CHANGELOG.md
  cmd2.py
  docs/conf.py
  examples/tab_completion.py
  setup.py
  tests/test_cmd2.py
  tests/test_completion.py
Labels: bug, enhancement

#354 Move to Python 3.4+ only
  .appveyor.yml
  .travis.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  cmd2.py
  docs/freefeatures.rst
  docs/index.rst
  docs/install.rst
  docs/requirements.txt
  examples/alias_startup.py
  examples/arg_print.py
  examples/argparse_example.py
  examples/environment.py
  examples/event_loops.py
  examples/example.py
  examples/help_categories.py
  examples/paged_output.py
  examples/persistent_history.py
  examples/pirate.py
  examples/python_scripting.py
  examples/remove_unused.py
  examples/subcommands.py
  examples/submenus.py
  examples/tab_completion.py
  examples/table_display.py
  setup.py
  tests/test_argparse.py
  tests/test_cmd2.py
  tests/test_completion.py
  tests/test_parsing.py
  tests/test_transcript.py
  tox.ini
Labels: documentation, enhancement, major

#360 Convert cmd2 to a multi-file Python package
  CONTRIBUTING.md
  cmd2/__init__.py
  cmd2/cmd2.py
  docs/install.rst
  setup.py
  tests/__init__.py
  tests/test_argparse.py
  tests/test_cmd2.py
  tests/test_parsing.py
  tests/test_submenu.py
  tests/test_transcript.py
Labels: enhancement, major

#363 Started adding type hints
  cmd2/cmd2.py
  cmd2/rl_utils.py
  examples/tab_autocompletion.py
Labels: enhancement

#365 Backport bugfix related to help completion on commands using with_arg…
  CHANGELOG.md
  cmd2.py
  tests/conftest.py
  tests/test_completion.py
Labels: bug

#366 argparse Autocompleter integration into cmd2
  CHANGELOG.md
  cmd2/argparse_completer.py
  cmd2/cmd2.py
  docs/argument_processing.rst
  examples/subcommands.py
  examples/tab_autocompletion.py
  tests/test_autocompletion.py
  tests/test_cmd2.py
  tests/test_completion.py
Labels: enhancement, major

#376 Fixed issue where completion display function was overwritten when a …
  cmd2/cmd2.py
Labels: bug
