Repository python-cmd2/cmd2, pull requests merged in 2018-06, with the labels that each got.

#424 Require minimum twine version for PyPI upload
  cmd2/cmd2.py
  docs/conf.py
  setup.py
  tasks.py
  tests/test_cmd2.py
Labels: bug, minor

#425 Add a couple unit tests for tokens_for_completion in argcomplete_bridge.py
  tests/test_bashcompletion.py
Labels: enhancement, minor

#428 Simplify subcommnads.py example
  examples/subcommands.py
Labels: enhancement, minor

#429 Added a unit test to help better cover rl_utils.py
  tests/test_cmd2.py
Labels: enhancement, minor

#432 Fixed a couple potential crashes on opening files
  CHANGELOG.md
  cmd2/cmd2.py
  tests/test_cmd2.py
  tests/test_transcript.py
Labels: bug

#433 Autocompleter
  cmd2/argparse_completer.py
  cmd2/cmd2.py
  examples/tab_autocompletion.py
Labels: enhancement

#434 Fix unexpected redirection behavior
  cmd2/cmd2.py
  cmd2/parsing.py
Labels: bug

#438 Enable a few more bash completion tests on TravisCI
  tests/test_bashcompletion.py
Labels: enhancement, minor

#439 Minor formatting changes to argcomplete_bridge.py
  cmd2/argcomplete_bridge.py
  tasks.py
Labels: enhancement, minor

#440 Improve type hinting
  .gitignore
  cmd2/__init__.py
  cmd2/argparse_completer.py
  cmd2/cmd2.py
  cmd2/pyscript_bridge.py
  cmd2/transcript.py
  cmd2/utils.py
  tests/test_cmd2.py
Labels: enhancement

#441 Added pager and pager_chop attributes to Cmd class
  CHANGELOG.md
  cmd2/cmd2.py
  examples/paged_output.py
Labels: enhancement, minor

#444 Updated CODEOWNERS to reflect who the experts are
  .gitignore
  CODEOWNERS
Labels: enhancement, minor

#451 Deprecated CmdResult helper class and promoted CommandResult
  CHANGELOG.md
  cmd2/__init__.py
  cmd2/cmd2.py
  cmd2/pyscript_bridge.py
  docs/argument_processing.rst
  examples/python_scripting.py
  examples/scripts/conditional.py
  tests/test_cmd2.py
Labels: enhancement, minor

#458 Fix bug for startup script with spaces
  cmd2/cmd2.py
Labels: bug

#455 "invoke clean" will now also cleanup mypy daemon artifacts
  tasks.py
Labels: enhancement, minor

#456 table_display.py example now uses tableformatter instead of tabulate
  CHANGELOG.md
  cmd2/cmd2.py
  docs/conf.py
  examples/table_display.py
  setup.py
  tests/test_cmd2.py
Labels: enhancement, minor
