Repository python-cmd2/cmd2, pull requests merged in 2018-10, with the labels that each got.

#565 Added title subcommand groups
  cmd2/cmd2.py
Labels: enhancement, minor

#568 Using sub-command instead of subcommand where possible to be consistent with argparse
  CHANGELOG.md
  cmd2/argparse_completer.py
  cmd2/cmd2.py
  cmd2/pyscript_bridge.py
  examples/subcommands.py
  examples/tab_autocomp_dynamic.py
  examples/tab_autocompletion.py
  examples/tab_completion.py
  tests/test_argparse.py
  tests/test_completion.py
  tests/test_pyscript.py
Labels: documentation, enhancement, minor

#570 set_window_title() will no longer write to stderr unless self._terminal_lock can be acquired
  cmd2/cmd2.py
Labels: bug, enhancement

#571 Fixes related to handling of argparse.REMAINDER
  CHANGELOG.md
  cmd2/argparse_completer.py
  cmd2/cmd2.py
  cmd2/pyscript_bridge.py
  cmd2/utils.py
  docs/argument_processing.rst
  examples/decorator_example.py
  examples/hello_cmd2.py
  examples/tab_autocompletion.py
  examples/table_display.py
  examples/transcripts/exampleSession.txt
  tests/test_acargparse.py
  tests/test_autocompletion.py
  tests/test_completion.py
  tests/test_pyscript.py
  tests/test_utils.py
Labels: bug, documentation, enhancement

#580 Add Env setup documentation in CONTRIBUTING
  CONTRIBUTING.md
Labels: documentation, enhancement

#583 Deleted Cmd.colorize() method and Cmd._colorcodes dictionary
  CHANGELOG.md
  cmd2/cmd2.py
  docs/unfreefeatures.rst
  tests/test_cmd2.py
Labels: enhancement, minor

#587 Ruggedized registration of SIGINT signal handler
  CHANGELOG.md
  cmd2/cmd2.py
  docs/settingchanges.rst
Labels: enhancement

#588 Fix redundant environments in tox.ini
  .appveyor.yml
  tox.ini
Labels: bug, minor

#589 Azure Pipelines build for macOS now runs tox instead of pytest
  azure-pipelines.yml
  setup.py
  tox.ini
Labels: enhancement

#592 Added path filtering ability to path_complete()
  CHANGELOG.md
  cmd2/cmd2.py
  cmd2/transcript.py
  docs/freefeatures.rst
  examples/python_scripting.py
  tests/test_completion.py
Labels: enhancement

#593 Improved README.md
  README.md
  cmd2/cmd2.py
  docs/argument_processing.rst
  setup.py
Labels: documentation, enhancement
