Repository python-cmd2/cmd2, pull requests merged in 2019-07, with the labels that each got.

#707 Redirect complete
  cmd2/cmd2.py
  tests/test_completion.py
Labels: enhancement

#708 Encapsulate all usage of colorama within ansi.py
  cmd2/ansi.py
  cmd2/cmd2.py
  cmd2/rl_utils.py
  examples/async_printing.py
  tests/test_ansi.py
Labels: enhancement

#710 Add Pipfile to support Pipenv for development
  .gitignore
  CONTRIBUTING.md
  Pipfile
  setup.py
  tasks.py
Labels: enhancement

#712 New Documentation Structure
  cmd2/cmd2.py
  cmd2/utils.py
  docs/alternatives.rst
  docs/api/cmd.rst
  docs/api/decorators.rst
  docs/api/exceptions.rst
  docs/api/index.rst
  docs/api/utility_classes.rst
  docs/api/utility_functions.rst
  docs/conf.py
  docs/copyright.rst
  docs/doc_conventions.rst
  docs/examples/first_app.rst
  docs/examples/index.rst
  docs/features/argument_processing.rst
  docs/features/clipboard.rst
  docs/features/commands.rst
  docs/features/completion.rst
  docs/features/disable_commands.rst
  docs/features/embedded_python_shells.rst
  docs/features/generating_output.rst
  docs/features/help.rst
  docs/features/history.rst
  docs/features/hooks.rst
  docs/features/index.rst
  docs/features/initialization.rst
  docs/features/multiline_commands.rst
  docs/features/os.rst
  docs/features/plugins.rst
  docs/features/prompt.rst
  docs/features/scripting.rst
  docs/features/settings.rst
  docs/features/shortcuts_aliases_macros.rst
  docs/features/startup_commands.rst
  docs/features/transcripts.rst
  docs/freefeatures.rst
  docs/index.rst
  docs/install.rst
  docs/integrating.rst
  docs/migrating/free_features.rst
  docs/migrating/incompatibilities.rst
  docs/migrating/index.rst
  docs/migrating/minimum.rst
  docs/migrating/nextsteps.rst
  docs/migrating/why.rst
  docs/overview.rst
  docs/overview/alternatives.rst
  docs/overview/index.rst
  docs/overview/installation.rst
  docs/overview/integrating.rst
  docs/overview/resources.rst
  docs/overview/summary.rst
  docs/settingchanges.rst
  docs/unfreefeatures.rst
  examples/example.py
  examples/first_app.py
  setup.py
  tasks.py
Labels: documentation

#715 Started filling in some missing stuff in the new documentation structure
  docs/index.rst
  docs/migrating/incompatibilities.rst
  docs/migrating/why.rst
Labels: documentation

#717 Restore self.statement_parser to a public attribute in cmd2.Cmd
  CHANGELOG.md
  cmd2/cmd2.py
  cmd2/parsing.py
  examples/hooks.py
  tests/test_cmd2.py
  tests/test_completion.py
Labels: bug

#720 Write documentation for migrating from cmd
  cmd2/cmd2.py
  docs/features/argument_processing.rst
  docs/features/clipboard.rst
  docs/features/embedded_python_shells.rst
  docs/features/generating_output.rst
  docs/features/index.rst
  docs/features/misc.rst
  docs/freefeatures.rst
  docs/index.rst
  docs/migrating/free_features.rst
  docs/migrating/incompatibilities.rst
  docs/migrating/index.rst
  docs/migrating/minimum.rst
  docs/migrating/next_steps.rst
  docs/migrating/nextsteps.rst
  docs/migrating/summary.rst
  docs/migrating/why.rst
  examples/example.py
  examples/migrating.py
Labels: documentation

#726 Integrate legacy documentation
  docs/examples/alternate_event_loops.rst
  docs/examples/index.rst
  docs/examples/removing_builtin_commands.rst
  docs/features/commands.rst
  docs/features/completion.rst
  docs/features/embedded_python_shells.rst
  docs/features/generating_output.rst
  docs/features/history.rst
  docs/features/misc.rst
  docs/features/os.rst
  docs/features/scripting.rst
  docs/features/settings.rst
  docs/features/shortcuts_aliases_macros.rst
  docs/features/transcripts.rst
  docs/freefeatures.rst
  docs/index.rst
  docs/integrating.rst
  docs/settingchanges.rst
  docs/unfreefeatures.rst
Labels: documentation

#732 Fix broken documentation links
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/index.rst
Labels: bug

#737 Changes made while preparing for PyOhio presentation
  CHANGELOG.md
  cmd2/__init__.py
  cmd2/argparse_completer.py
  cmd2/argparse_custom.py
  cmd2/cmd2.py
  cmd2/py_bridge.py
  tests/pyscript/stop.py
  tests/test_argparse_completer.py
  tests/test_cmd2.py
  tests/test_run_pyscript.py
Labels: bug, enhancement
