Repository python-cmd2/cmd2, pull requests merged in 2019-05, with the labels that each got.

#679 Appveyor fix
  .appveyor.yml
Labels: bug

#676 Pipe chaining
  .travis.yml
  CHANGELOG.md
  cmd2/argparse_completer.py
  cmd2/cmd2.py
  cmd2/parsing.py
  cmd2/utils.py
  tasks.py
  tests/conftest.py
  tests/test_cmd2.py
  tests/test_completion.py
  tests/test_parsing.py
Labels: bug, enhancement, major

#681 Ns provider
  CHANGELOG.md
  cmd2/cmd2.py
  docs/argument_processing.rst
  tests/test_argparse.py
Labels: enhancement

#685 Refactor exit_code implementation
  CHANGELOG.md
  README.md
  cmd2/cmd2.py
  cmd2/transcript.py
  docs/unfreefeatures.rst
  examples/alias_startup.py
  examples/arg_print.py
  examples/async_printing.py
  examples/cmd_as_argument.py
  examples/colors.py
  examples/decorator_example.py
  examples/environment.py
  examples/example.py
  examples/exit_code.py
  examples/hello_cmd2.py
  examples/help_categories.py
  examples/hooks.py
  examples/paged_output.py
  examples/persistent_history.py
  examples/pirate.py
  examples/plumbum_colors.py
  examples/python_scripting.py
  examples/remove_unused.py
  examples/subcommands.py
  examples/tab_autocomp_dynamic.py
  examples/tab_autocompletion.py
  examples/tab_completion.py
  examples/table_display.py
  tests/test_cmd2.py
  tests/test_transcript.py
  tests/transcripts/failure.txt
Labels: bug, enhancement
