Repository python-cmd2/cmd2, pull requests merged in 2019-06, with the labels that each got.

#689 Persistent history for #669
  .gitignore
  CHANGELOG.md
  cmd2/cmd2.py
  cmd2/history.py
  docs/freefeatures.rst
  examples/hello_cmd2.py
  tests/conftest.py
  tests/test_history.py
Labels: enhancement, major

#699 History fixes
  CHANGELOG.md
  cmd2/cmd2.py
  cmd2/history.py
  examples/cmd_as_argument.py
  tests/test_cmd2.py
  tests/test_history.py
  tests/test_parsing.py
Labels: bug

#700 Deprecate Python 3.4 and add support and testing for Python 3.8
  .travis.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  azure-pipelines.yml
  cmd2/cmd2.py
  cmd2/pyscript_bridge.py
  docs/index.rst
  docs/install.rst
  setup.py
  tests/conftest.py
  tox.ini
Labels: enhancement

#703 Minimize public API of cmd2.Cmd class
  CHANGELOG.md
  README.md
  cmd2/__init__.py
  cmd2/cmd2.py
  cmd2/constants.py
  cmd2/parsing.py
  cmd2/pyscript_bridge.py
  cmd2/transcript.py
  cmd2/utils.py
  docs/argument_processing.rst
  docs/settingchanges.rst
  examples/arg_print.py
  examples/cmd_as_argument.py
  examples/colors.py
  examples/decorator_example.py
  examples/example.py
  examples/hooks.py
  examples/pirate.py
  examples/plumbum_colors.py
  examples/python_scripting.py
  examples/scripts/conditional.py
  tests/conftest.py
  tests/test_cmd2.py
  tests/test_completion.py
  tests/test_transcript.py
  tests/test_utils.py
  tests/transcripts/from_cmdloop.txt
Labels: enhancement

#704 #698 - Revisiting Color Support
  CHANGELOG.md
  README.md
  cmd2/ansi.py
  cmd2/argparse_completer.py
  cmd2/cmd2.py
  cmd2/constants.py
  cmd2/history.py
  cmd2/parsing.py
  cmd2/transcript.py
  cmd2/utils.py
  docs/argument_processing.rst
  docs/settingchanges.rst
  docs/unfreefeatures.rst
  examples/async_printing.py
  examples/colors.py
  examples/paged_output.py
  examples/pirate.py
  examples/plumbum_colors.py
  examples/python_scripting.py
  examples/table_display.py
  tests/conftest.py
  tests/scripts/postcmds.txt
  tests/scripts/precmds.txt
  tests/test_ansi.py
  tests/test_cmd2.py
  tests/test_history.py
  tests/test_utils.py
  tests/transcripts/regex_set.txt
Labels: enhancement, major

#706 Remove load, _relative_load, pyscript aliases
  CHANGELOG.md
  cmd2/clipboard.py
  cmd2/cmd2.py
  docs/integrating.rst
  docs/unfreefeatures.rst
  examples/transcripts/exampleSession.txt
  examples/transcripts/transcript_regex.txt
  setup.py
  tests/.cmd2rc
  tests/test_cmd2.py
  tests/test_run_pyscript.py
Labels: enhancement, minor
