Repository python-cmd2/cmd2, pull requests merged in 2019-09, with the labels that each got.

#769 Fix what is fundamentally a Pyperclip bug on headless Linux systems w…
  CHANGELOG.md
  cmd2/clipboard.py
  cmd2/cmd2.py
  tests/test_cmd2.py
Labels: bug

#775 Added a basic example for dynamically adding do_* commands in a loop
  CHANGELOG.md
  cmd2/cmd2.py
  examples/dynamic_commands.py
Labels: documentation, enhancement

#774 Completion state
  CHANGELOG.md
  cmd2/argparse_completer.py
  cmd2/argparse_custom.py
  cmd2/cmd2.py
  tests/test_argparse_completer.py
  tests/test_completion.py
Labels: enhancement

#776 Missing subcommand no longer prints all help text
  cmd2/cmd2.py
  tests/test_cmd2.py
  tests/test_completion.py
  tests/test_transcript.py
Labels: enhancement

#780 Doc additions
  docs/examples/index.rst
  docs/examples/removing_builtin_commands.rst
  docs/features/commands.rst
  docs/features/disable_commands.rst
  docs/features/help.rst
  examples/remove_builtin_commands.py
Labels: documentation
