Repository python-cmd2/cmd2, pull requests merged in 2019-03, with the labels that each got.

#630 Pyscript overhaul
  CHANGELOG.md
  README.md
  cmd2/argparse_completer.py
  cmd2/cmd2.py
  cmd2/pyscript_bridge.py
  cmd2/utils.py
  tests/pyscript/bar1.py
  tests/pyscript/custom_echo.py
  tests/pyscript/foo1.py
  tests/pyscript/foo2.py
  tests/pyscript/foo3.py
  tests/pyscript/foo4.py
  tests/pyscript/help.py
  tests/pyscript/help_media.py
  tests/pyscript/media_movies_add1.py
  tests/pyscript/media_movies_add2.py
  tests/pyscript/media_movies_list1.py
  tests/pyscript/media_movies_list2.py
  tests/pyscript/media_movies_list3.py
  tests/pyscript/media_movies_list4.py
  tests/pyscript/media_movies_list5.py
  tests/pyscript/media_movies_list6.py
  tests/pyscript/media_movies_list7.py
  tests/pyscript/pyscript_dir.py
  tests/pyscript/pyscript_dir2.py
  tests/test_pyscript.py
Labels: bug, enhancement

#635 Improvements to history command
  CHANGELOG.md
  cmd2/cmd2.py
  cmd2/constants.py
  cmd2/history.py
  cmd2/parsing.py
  tests/conftest.py
  tests/test_cmd2.py
  tests/test_history.py
  tests/test_parsing.py
  tests/transcripts/from_cmdloop.txt
Labels: bug, enhancement

#636 Fix bug in with_argument_list decorator
  CHANGELOG.md
  cmd2/cmd2.py
  docs/freefeatures.rst
  examples/arg_print.py
  tests/test_argparse.py
Labels: bug

#638 Added a shlex.split() wrapper to have a common way of calling it.
  cmd2/cmd2.py
  cmd2/parsing.py
  tests/test_argparse.py
Labels: enhancement, minor

#642 StdSim.pause_storage
  CHANGELOG.md
  cmd2/pyscript_bridge.py
  cmd2/utils.py
  docs/freefeatures.rst
  tests/test_utils.py
Labels: enhancement

#643 Disable commands
  CHANGELOG.md
  cmd2/cmd2.py
  docs/argument_processing.rst
  docs/unfreefeatures.rst
  examples/help_categories.py
  tests/test_cmd2.py
Labels: enhancement

#645 History improvements
  cmd2/cmd2.py
  cmd2/history.py
  docs/freefeatures.rst
  tests/test_history.py
  tests/test_transcript.py
Labels: documentation, enhancement

#646 Disabling tweaks
  CHANGELOG.md
  cmd2/cmd2.py
  examples/help_categories.py
  tests/test_cmd2.py
Labels: enhancement

#647 Help now writes to stderr when no help information is found
  CHANGELOG.md
  cmd2/cmd2.py
  tests/test_cmd2.py
Labels: enhancement

#650 Use README.md as the PyPI long description
  setup.py
Labels: enhancement, minor

#649 Cmd line
  CHANGELOG.md
  cmd2/cmd2.py
  cmd2/parsing.py
  docs/argument_processing.rst
  examples/decorator_example.py
  tests/test_parsing.py
Labels: enhancement

#648 Converted class attributes to instance attributes
  CHANGELOG.md
  README.md
  cmd2/clipboard.py
  cmd2/cmd2.py
  cmd2/history.py
  cmd2/parsing.py
  cmd2/pyscript_bridge.py
  cmd2/rl_utils.py
  cmd2/utils.py
  docs/settingchanges.rst
  docs/unfreefeatures.rst
  examples/arg_print.py
  examples/async_printing.py
  examples/cmd_as_argument.py
  examples/colors.py
  examples/decorator_example.py
  examples/example.py
  examples/hooks.py
  examples/pirate.py
  examples/plumbum_colors.py
  tests/test_cmd2.py
  tests/test_completion.py
  tests/test_transcript.py
Labels: enhancement

#652 Added load -t flag for recording a transcript based on a script file
  CHANGELOG.md
  cmd2/cmd2.py
  docs/freefeatures.rst
  docs/transcript.rst
  tests/scripts/help.txt
  tests/test_transcript.py
Labels: enhancement

#656 Multiline prompt
  CHANGELOG.md
  cmd2/cmd2.py
  examples/async_printing.py
Labels: bug, minor
