Repository python-cmd2/cmd2, pull requests merged in 2020-04, with the labels that each got.

#911 The continuation_prompt attribute was declared twice in cmd.rst
  cmd2/cmd2.py
  docs/api/cmd.rst
Labels: bug, documentation

#915 Added documentation about decorator order and updated an example
  docs/conf.py
  docs/features/argument_processing.rst
  examples/help_categories.py
Labels: bug, documentation

#924 Command function wrappers now pass kwargs through to wrapped function
  CHANGELOG.md
  cmd2/cmd2.py
  cmd2/decorators.py
  tests/test_argparse.py
Labels: enhancement

#916 Initial commit of table creation API
  CHANGELOG.md
  cmd2/argparse_completer.py
  cmd2/argparse_custom.py
  cmd2/cmd2.py
  cmd2/constants.py
  cmd2/table_creator.py
  cmd2/utils.py
  docs/api/index.rst
  docs/api/table_creator.rst
  docs/api/utils.rst
  docs/features/index.rst
  docs/features/table_creation.rst
  examples/table_creation.py
  examples/table_display.py
  tests/test_argparse_custom.py
  tests/test_cmd2.py
  tests/test_table_creator.py
  tests/test_utils.py
Labels: enhancement

#927 Fix unit test which made incorrect assumption about vi editor
  tests/test_cmd2.py
Labels: bug

#931 Added info on SemVer and branching strategy to CONTRIBUTING.md
  CONTRIBUTING.md
  Pipfile
  cmd2/ansi.py
  cmd2/argparse_completer.py
  cmd2/argparse_custom.py
  cmd2/cmd2.py
  cmd2/history.py
  cmd2/parsing.py
  cmd2/py_bridge.py
  cmd2/rl_utils.py
  docs/conf.py
  examples/alias_startup.py
  examples/argparse_completion.py
  examples/async_printing.py
  examples/basic.py
  examples/colors.py
  examples/custom_parser.py
  examples/exit_code.py
  examples/hooks.py
  examples/initialization.py
  examples/migrating.py
  examples/override_parser.py
  examples/plumbum_colors.py
  examples/scripts/arg_printer.py
  examples/subcommands.py
  examples/unicode_commands.py
  setup.cfg
  setup.py
  tasks.py
  tests/conftest.py
  tests/pyscript/environment.py
  tests/test_argparse.py
  tests/test_argparse_completer.py
  tests/test_argparse_custom.py
  tests/test_cmd2.py
  tests/test_completion.py
  tests/test_history.py
  tests/test_parsing.py
  tests/test_plugin.py
  tests/test_run_pyscript.py
  tests/test_table_creator.py
  tests/test_transcript.py
Labels: documentation, enhancement
